BUTTONS:
  DOWNLOAD: '⤵ Ввести ссылку'
  CANCEL: '❌ Отмена'
WEB_SERVER_HOST: '127.0.0.1'
WEB_SERVER_PORT: 8090
WEBHOOK_PATH: '/wh'
BASE_WEBHOOK_URL: 'https://bot.voidspace.ru'
LOG_FILENAME: ''
DATE_FMT: '%Y-%m-%d %H:%M:%S'
LOG_FMT: '{time} [{level}] {message}'
